### ISSUE TITLE
cljx files are not automatically recompiled

### ISSUE THREAD

**Issue by mmower** [jakemcc/lein-autoexpect#10]
Hi.

Running "lein autoexpect" compiles my cljx files as expected. But when ones of those files is changed the cljx files are not recompiled so no new clj files are generated and the expectations are not run.

Any ideas what I might be doing wrong here?

Note that I've tried working around this by running "lein cljx auto" in one session and "lein autoexpect" in another. This sort of works but sometimes the tests are run before all the source transformations have taken place leading to tests passing (or, I presume, failing) when they shouldn't.

Kind regards,

Matt

**Comment by jakemcc** [comment]
Closing this now that reader conditionals exist and cljc is the way forward.
